### ISSUE TITLE
About model and code

### ISSUE THREAD

**Issue by chiaki-luo** [hayeong0/Diff-HierVC#1]
Dear author, thank you for your outstanding work. I am also very interested in this paper and the diffusion model for pitch generator. I wonder when the source code and the specific training model can be made public.  Thank you!

**Comment by hayeong0** [comment]
Thank you for your interest in our work.
I apologize for the delayed response. 😢
Due to our subsequent works, the release of the code was postponed.
We have now uploaded the model and inference code. 
Please feel free to check and use it. Thanks.

**Comment by chiaki-luo** [comment]
@hayeong0 Thank you very much!!!
