### ISSUE TITLE
There is any plan to release the source train code?

### ISSUE THREAD

**Issue by AntroFyo** [hayeong0/Diff-HierVC#2]

**Comment by hayeong0** [comment]
We are currently conducting follow-up research related to this work. So, we plan to organize and share the training code by the end of December or the beginning of January. 
Thanks for your patience and understanding.

**Comment by mysxs** [comment]
I hope you can release the train code as soon as possible, thanks!!

**Comment by AshwinSankar17** [comment]
Hello. Impressive results! Looking forward to trying this model out on my dataset.  When can we expect the training code release?

**Comment by hayeong0** [comment]
Sorry for the late reply, I'm planning on sharing throughout January!

**Comment by skol101** [comment]
> Sorry for the late reply, I'm planning on sharing throughout January!

Any update on this?

**Comment by markrmiller** [comment]
Any chance the training code is still coming?
