### ISSUE TITLE
bigvgan

### ISSUE THREAD

**Issue by bigdan12** [hayeong0/Diff-HierVC#4]
The config may not be correct, please update it.

**Comment by hayeong0** [comment]
I've updated it now. Please check it.

**Comment by weirenlan** [comment]
@hayeong0 Thanks for your research
I try to inference with bigvan by this setting 
```
bash infer.sh

python3 inference.py \
    --src_path './sample/src_p241_004.wav' \
    --trg_path './sample/tar_p239_022.wav' \
    --ckpt_model './ckpt/model_diffhier.pth' \
    --ckpt_voc './vocoder/voc_bigvgan.pth' \
    --output_dir './converted' \
    --diffpitch_ts 30 \
    --diffvoice_ts 6
 ```
 and adjust the config with
    
  ```
        config = os.path.join(os.path.split(a.ckpt_model)[0], 'config_bigvgan.json')  
  ```
  
  But the converted result seems like strange
  
<img width="393" alt="image" src="https://github.com/hayeong0/Diff-HierVC/assets/76981114/4f9dac03-b5a4-41db-bb06-d7f94dfb249e">

**Comment by hayeong0** [comment]
@weirenlan 

We didn't encounter any issues when performing inference with our existing code. 
The results you posted seem to indicate that Bigvgan has not been loaded. 
I have made some simplifications to the code to make it easier. 
Please try again with the updated code and make sure to check the location where you downloaded the checkpoint file :)

**Comment by weirenlan** [comment]
@hayeong0 Thanks for your updating. After the updating, the export is correct and awesome~
