### ISSUE TITLE
Getting 'Hparams' has no attribute 'hidden_size' when running infer.sh

### ISSUE THREAD

**Issue by Guruprasad68** [hayeong0/Diff-HierVC#8]
Hi, 
I am getting the following error when I ran infer.sh with the biggan Vocoder. I am not pasting the full traceback as it contains some sensitive paths. My python version is 3.10 and I didn't follow the same versions as given in the requirements.txt file as there were issues in installing natten with the version of pytorch given in that file. So I used 2.0.0 pytorch along with natten 0.17.1 . It will be great if you guys can add what python version you are using to run the model and a full package list with requisite dependencies. 
```model = DiffHierVC(hps.data.n_mel_channels, hps.diffusion.spk_dim,
  File "<pathto>/Diff-HierVC/model/diffhiervc.py", line 133, in __init__
    self.encoder = SynthesizerTrn(hps.model.hidden_size)
AttributeError: 'HParams' object has no attribute 'hidden_size' 

```

**Comment by hayeong0** [comment]
Hello, sorry for the confusion. The package you mentioned is not used in the code from this repository. 
Also, I have changed the variable name from `encoder_hidden_size` to `hidden_size` while updating the entire forward code. This change has also been reflected in the config. (ckpt/config.json)

Thanks.

**Comment by Guruprasad68** [comment]
Thanks for the update. The requirements.txt file has 'natten==0.14.6'

**Comment by Guruprasad68** [comment]
I pulled the latest code and ran infer.sh again.  Getting this error now. 
```pred_f0[f0_zeros_mask.expand_as(pred_f0)] = 0 
RuntimeError: expand(CUDABoolType{[1, 1, 1, 864]}, size=[1, 1, 864]): the number of sizes provided (3) must be greater or equal to the number of dimensions in the tensor (4)
```

**Comment by hayeong0** [comment]
Oh my mistake, I corrected it!

**Comment by Guruprasad68** [comment]
Thanks a lot for the changes. It works now
