### ISSUE TITLE
About the parameters of train.py 

### ISSUE THREAD

**Issue by xinxinye000** [hayeong0/Diff-HierVC#9]
When I run train.py, I'm asked to input --config and --model, and I want to know what those two are. I've tried training./model/base.py and./module/modules.py, but the weights I get are like g_10,000.pt, Can these be used in inference? Once the inference is run, the error will be as follows:

D:\Anaconda\000\envs\cuda113\python.exe E:\Code_test\88_wav-wav\01\Diff-HierVC-master\inference.py 
>> Initializing Inference Process...
Traceback (most recent call last):
  File "E:\Code_test\88_wav-wav\01\Diff-HierVC-master\inference.py", line 140, in <module>
    main()
  File "E:\Code_test\88_wav-wav\01\Diff-HierVC-master\inference.py", line 137, in main
    inference(a)
  File "E:\Code_test\88_wav-wav\01\Diff-HierVC-master\inference.py", line 70, in inference
    model.load_state_dict(torch.load(a.ckpt_model))
  File "D:\Anaconda\000\envs\cuda113\lib\site-packages\torch\nn\modules\module.py", line 1497, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DiffHierVC:
	Missing key(s) in state_dict: "encoder.emb_c.weight", "encoder.emb_c.bias", "encoder.emb_c_f0.weight", "encoder.emb_c_f0.bias", "encoder.emb_f0.weight", "encoder.emb_f0.bias", "encoder.emb_norm_f0.weight", "encoder.emb_norm_f0.bias", "encoder.emb_g.spectral.0.weight", "encoder.emb_g.spectral.0.bias", "encoder.emb_g.spectral.3.weight", "encoder.emb_g.spectral.3.bias", "encoder.emb_g.temporal.0.conv1.weight", "encoder.emb_g.temporal.0.conv1.bias", "encoder.emb_g.temporal.1.conv1.weight", "encoder.emb_g.temporal.1.conv1.bias", "encoder.emb_g.slf_attn.conv_q.weight", "encoder.emb_g.slf_attn.conv_q.bias", "encoder.emb_g.slf_attn.conv_k.weight", "encoder.emb_g.slf_attn.conv_k.bias", "encoder.emb_g.slf_attn.conv_v.weight", "encoder.emb_g.slf_attn.conv_v.bias", "encoder.emb_g.slf_attn.conv_o.weight", "encoder.emb_g.slf_attn.conv_o.bias", "encoder.emb_g.fc.weight", "encoder.emb_g.fc.bias", "encoder.mel_enc_c.pre.weight", "encoder.mel_enc_c.pre.bias", "encoder.mel_enc_c.enc.in_layers.0.bias", "encoder.mel_enc_c.enc.in_layers.0.weight_g", "encoder.mel_enc_c.enc.in_layers.0.weight_v", "encoder.mel_enc_c.enc.in_layers.1.bias", "encoder.mel_enc_c.enc.in_layers.1.weight_g", "encoder.mel_enc_c.enc.in_layers.1.weight_v", "encoder.mel_enc_c.enc.in_layers.2.bias", "encoder.mel_enc_c.enc.in_layers.2.weight_g", "encoder.mel_enc_c.enc.in_layers.2.weight_v", "encoder.mel_enc_c.enc.in_layers.3.bias", "encoder.mel_enc_c.enc.in_layers.3.weight_g", "encoder.mel_enc_c.enc.in_layers.3.weight_v", "encoder.mel_enc_c.enc.in_layers.4.bias", "encoder.mel_enc_c.enc.in_layers.4.weight_g", "encoder.mel_enc_c.enc.in_layers.4.weight_v", "encoder.mel_enc_c.enc.in_layers.5.bias", "encoder.mel_enc_c.enc.in_layers.5.weight_g", "encoder.mel_enc_c.enc.in_layers.5.weight_v", "encoder.mel_enc_c.enc.in_layers.6.bias", "encoder.mel_enc_c.enc.in_layers.6.weight_g", "encoder.mel_enc_c.enc.in_layers.6.weight_v", "encoder.mel_enc_c.enc.in_layers.7.bias", "encoder.mel_enc_c.enc.in_layers.7.weight_g", "encoder.mel_enc_c.enc.in_layers.7.weight_v", "encoder.mel_enc_c.enc.res_skip_layers.0.bias", "encoder.mel_enc_c.enc.res_skip_layers.0.weight_g", "encoder.mel_enc_c.enc.res_skip_layers.0.weight_v", "encoder.mel_enc_c.enc.res_skip_layers.1.bias", "encoder.mel_enc_c.enc.res_skip_layers.1.weight_g", "encoder.mel_enc_c.enc.res_skip_layers.1.weight_v", "encoder.mel_enc_c.enc.res_skip_layers.2.bias", "encoder.mel_enc_c.enc.res_skip_layers.2.weight_g", "encoder.mel_enc_c.enc.res_skip_layers.2.weight_v", "encoder.mel_enc_c.enc.res_skip_layers.3.bias", "encoder.mel_enc_c.enc.res_skip_layers.3.weight_g", "encoder.mel_enc_c.enc.res_skip_layers.3.weight_v", "encoder.mel_enc_c.enc.res_skip_layers.4.bias", "encoder.mel_enc_c.enc.res_skip_layers.4.weight_g", "encoder.mel_enc_c.enc.res_skip_layers.4.weight_v", "encoder.mel_enc_c.enc.res_skip_layers.5.bias", "encoder.mel_enc_c.enc.res_skip_layers.5.weight_g", "encoder.mel_enc_c.enc.res_skip_layers.5.weight_v", "encoder.mel_enc_c.enc.res_skip_layers.6.bias", "encoder.mel_enc_c.enc.res_skip_layers.6.weight_g", "encoder.mel_enc_c.enc.res_skip_layers.6.weight_v", "encoder.mel_enc_c.enc.res_skip_layers.7.bias", "encoder.mel_enc_c.enc.res_skip_layers.7.weight_g", "encoder.mel_enc_c.enc.res_skip_layers.7.weight_v", "encoder.mel_enc_c.enc.cond_layer.bias", "encoder.mel_enc_c.enc.cond_layer.weight_g", "encoder.mel_enc_c.enc.cond_layer.weight_v", "encoder.mel_enc_c.proj.weight", "encoder.mel_enc_c.proj.bias", "encoder.mel_enc_f.pre.weight", "encoder.mel_enc_f.pre.bias", "encoder.mel_enc_f.enc.in_layers.0.bias", "encoder.mel_enc_f.enc.in_layers.0.weight_g", "encoder.mel_enc_f.enc.in_layers.0.weight_v", "encoder.mel_enc_f.enc.in_layers.1.bias", "encoder.mel_enc_f.enc.in_layers.1.weight_g", "encoder.mel_enc_f.enc.in_layers.1.weight_v", "encoder.mel_enc_f.enc.in_layers.2.bias", "encoder.mel_enc_f.enc.in_layers.2.weight_g", "encoder.mel_enc_f.enc.in_layers.2.weight_v", "encoder.mel_enc_f.enc.in_layers.3.bias", "encoder.mel_enc_f.enc.in_layers.3.weight_g", "encoder.mel_enc_f.enc.in_layers.3.weight_v", "encoder.mel_enc_f.enc.in_layers.4.bias", "encoder.mel_enc_f.enc.in_layers.4.weight_g", "encoder.mel_enc_f.enc.in_layers.4.weight_v", "encoder.mel_enc_f.enc.in_layers.5.bias", "encoder.mel_enc_f.enc.in_layers.5.weight_g", "encoder.mel_enc_f.enc.in_layers.5.weight_v", "encoder.mel_enc_f.enc.in_layers.6.bias", "encoder.mel_enc_f.enc.in_layers.6.weight_g", "encoder.mel_enc_f.enc.in_layers.6.weight_v", "encoder.mel_enc_f.enc.in_layers.7.bias", "encoder.mel_enc_f.enc.in_layers.7.weight_g", "encoder.mel_enc_f.enc.in_layers.7.weight_v", "encoder.mel_enc_f.enc.res_skip_layers.0.bias", "encoder.mel_enc_f.enc.res_skip_layers.0.weight_g", "encoder.mel_enc_f.enc.res_skip_layers.0.weight_v", "encoder.mel_enc_f.enc.res_skip_layers.1.bias", "encoder.mel_enc_f.enc.res_skip_layers.1.weight_g", "encoder.mel_enc_f.enc.res_skip_layers.1.weight_v", "encoder.mel_enc_f.enc.res_skip_layers.2.bias", "encoder.mel_enc_f.enc.res_skip_layers.2.weight_g", "encoder.mel_enc_f.enc.res_skip_layers.2.weight_v", "encoder.mel_enc_f.enc.res_skip_layers.3.bias", "encoder.mel_enc_f.enc.res_skip_layers.3.weight_g", "encoder.mel_enc_f.enc.res_skip_layers.3.weight_v", "encoder.mel_enc_f.enc.res_skip_layers.4.bias", "encoder.mel_enc_f.enc.res_skip_layers.4.weight_g", "encoder.mel_enc_f.enc.res_skip_layers.4.weight_v", "encoder.mel_enc_f.enc.res_skip_layers.5.bias", "encoder.mel_enc_f.enc.res_skip_layers.5.weight_g", "encoder.mel_enc_f.enc.res_skip_layers.5.weight_v", "encoder.mel_enc_f.enc.res_skip_layers.6.bias", "encoder.mel_enc_f.enc.res_skip_layers.6.weight_g", "encoder.mel_enc_f.enc.res_skip_layers.6.weight_v", "encoder.mel_enc_f.enc.res_skip_layers.7.bias", "encoder.mel_enc_f.enc.res_skip_layers.7.weight_g", "encoder.mel_enc_f.enc.res_skip_layers.7.weight_v", "encoder.mel_enc_f.enc.cond_layer.bias", "encoder.mel_enc_f.enc.cond_layer.weight_g", "encoder.mel_enc_f.enc.cond_layer.weight_v", "encoder.mel_enc_f.proj.weight", "encoder.mel_enc_f.proj.bias", "encoder.f0_enc.pre.weight", "encoder.f0_enc.pre.bias", "encoder.f0_enc.enc.in_layers.0.bias", "encoder.f0_enc.enc.in_layers.0.weight_g", "encoder.f0_enc.enc.in_layers.0.weight_v", "encoder.f0_enc.enc.in_layers.1.bias", "encoder.f0_enc.enc.in_layers.1.weight_g", "encoder.f0_enc.enc.in_layers.1.weight_v", "encoder.f0_enc.enc.in_layers.2.bias", "encoder.f0_enc.enc.in_layers.2.weight_g", "encoder.f0_enc.enc.in_layers.2.weight_v", "encoder.f0_enc.enc.in_layers.3.bias", "encoder.f0_enc.enc.in_layers.3.weight_g", "encoder.f0_enc.enc.in_layers.3.weight_v", "encoder.f0_enc.enc.in_layers.4.bias", "encoder.f0_enc.enc.in_layers.4.weight_g", "encoder.f0_enc.enc.in_layers.4.weight_v", "encoder.f0_enc.enc.in_layers.5.bias", "encoder.f0_enc.enc.in_layers.5.weight_g", "encoder.f0_enc.enc.in_layers.5.weight_v", "encoder.f0_enc.enc.in_layers.6.bias", "encoder.f0_enc.enc.in_layers.6.weight_g", "encoder.f0_enc.enc.in_layers.6.weight_v", "encoder.f0_enc.enc.in_layers.7.bias", "encoder.f0_enc.enc.in_layers.7.weight_g", "encoder.f0_enc.enc.in_layers.7.weight_v", "encoder.f0_enc.enc.res_skip_layers.0.bias", "encoder.f0_enc.enc.res_skip_layers.0.weight_g", "encoder.f0_enc.enc.res_skip_layers.0.weight_v", "encoder.f0_enc.enc.res_skip_layers.1.bias", "encoder.f0_enc.enc.res_skip_layers.1.weight_g", "encoder.f0_enc.enc.res_skip_layers.1.weight_v", "encoder.f0_enc.enc.res_skip_layers.2.bias", "encoder.f0_enc.enc.res_skip_layers.2.weight_g", "encoder.f0_enc.enc.res_skip_layers.2.weight_v", "encoder.f0_enc.enc.res_skip_layers.3.bias", "encoder.f0_enc.enc.res_skip_layers.3.weight_g", "encoder.f0_enc.enc.res_skip_layers.3.weight_v", "encoder.f0_enc.enc.res_skip_layers.4.bias", "encoder.f0_enc.enc.res_skip_layers.4.weight_g", "encoder.f0_enc.enc.res_skip_layers.4.weight_v", "encoder.f0_enc.enc.res_skip_layers.5.bias", "encoder.f0_enc.enc.res_skip_layers.5.weight_g", "encoder.f0_enc.enc.res_skip_layers.5.weight_v", "encoder.f0_enc.enc.res_skip_layers.6.bias", "encoder.f0_enc.enc.res_skip_layers.6.weight_g", "encoder.f0_enc.enc.res_skip_layers.6.weight_v", "encoder.f0_enc.enc.res_skip_layers.7.bias", "encoder.f0_enc.enc.res_skip_layers.7.weight_g", "encoder.f0_enc.enc.res_skip_layers.7.weight_v", "encoder.f0_enc.enc.cond_layer.bias", "encoder.f0_enc.enc.cond_layer.weight_g", "encoder.f0_enc.enc.cond_layer.weight_v", "encoder.f0_enc.proj.weight", "encoder.f0_enc.proj.bias", "encoder.proj.weight", "encoder.proj.bias", "f0_dec.estimator_f0.mlp.0.weight", "f0_dec.estimator_f0.mlp.0.bias", "f0_dec.estimator_f0.mlp.2.weight", "f0_dec.estimator_f0.mlp.2.bias", "f0_dec.estimator_f0.cond_block.0.weight", "f0_dec.estimator_f0.cond_block.0.bias", "f0_dec.estimator_f0.cond_block.2.weight", "f0_dec.estimator_f0.cond_block.2.bias", "f0_dec.estimator_f0.input_projection.0.weight", "f0_dec.estimator_f0.input_projection.0.bias", "f0_dec.estimator_f0.residual_layers.0.dilated_conv.weight", "f0_dec.estimator_f0.residual_layers.0.dilated_conv.bias", "f0_dec.estimator_f0.residual_layers.0.diffusion_projection.weight", "f0_dec.estimator_f0.residual_layers.0.diffusion_projection.bias", "f0_dec.estimator_f0.residual_layers.0.conditioner_projection.weight", "f0_dec.estimator_f0.residual_layers.0.conditioner_projection.bias", "f0_dec.estimator_f0.residual_layers.0.output_projection.weight", "f0_dec.estimator_f0.residual_layers.0.output_projection.bias", "f0_dec.estimator_f0.residual_layers.1.dilated_conv.weight", "f0_dec.estimator_f0.residual_layers.1.dilated_conv.bias", "f0_dec.estimator_f0.residual_layers.1.diffusion_projection.weight", "f0_dec.estimator_f0.residual_layers.1.diffusion_projection.bias", "f0_dec.estimator_f0.residual_layers.1.conditioner_projection.weight", "f0_dec.estimator_f0.residual_layers.1.conditioner_projection.bias", "f0_dec.estimator_f0.residual_layers.1.output_projection.weight", "f0_dec.estimator_f0.residual_layers.1.output_projection.bias", "f0_dec.estimator_f0.residual_layers.2.dilated_conv.weight", "f0_dec.estimator_f0.residual_layers.2.dilated_conv.bias", "f0_dec.estimator_f0.residual_layers.2.diffusion_projection.weight", "f0_dec.estimator_f0.residual_layers.2.diffusion_projection.bias", "f0_dec.estimator_f0.residual_layers.2.conditioner_projection.weight", "f0_dec.estimator_f0.residual_layers.2.conditioner_projection.bias", "f0_dec.estimator_f0.residual_layers.2.output_projection.weight", "f0_dec.estimator_f0.residual_layers.2.output_projection.bias", "f0_dec.estimator_f0.residual_layers.3.dilated_conv.weight", "f0_dec.estimator_f0.residual_layers.3.dilated_conv.bias", "f0_dec.estimator_f0.residual_layers.3.diffusion_projection.weight", "f0_dec.estimator_f0.residual_layers.3.diffusion_projection.bias", "f0_dec.estimator_f0.residual_layers.3.conditioner_projection.weight", "f0_dec.estimator_f0.residual_layers.3.conditioner_projection.bias", "f0_dec.estimator_f0.residual_layers.3.output_projection.weight", "f0_dec.estimator_f0.residual_layers.3.output_projection.bias", "f0_dec.estimator_f0.residual_layers.4.dilated_conv.weight", "f0_dec.estimator_f0.residual_layers.4.dilated_conv.bias", "f0_dec.estimator_f0.residual_layers.4.diffusion_projection.weight", "f0_dec.estimator_f0.residual_layers.4.diffusion_projection.bias", "f0_dec.estimator_f0.residual_layers.4.conditioner_projection.weight", "f0_dec.estimator_f0.residual_layers.4.conditioner_projection.bias", "f0_dec.estimator_f0.residual_layers.4.output_projection.weight", "f0_dec.estimator_f0.residual_layers.4.output_projection.bias", "f0_dec.estimator_f0.residual_layers.5.dilated_conv.weight", "f0_dec.estimator_f0.residual_layers.5.dilated_conv.bias", "f0_dec.estimator_f0.residual_layers.5.diffusion_projection.weight", "f0_dec.estimator_f0.residual_layers.5.diffusion_projection.bias", "f0_dec.estimator_f0.residual_layers.5.conditioner_projection.weight", "f0_dec.estimator_f0.residual_layers.5.conditioner_projection.bias", "f0_dec.estimator_f0.residual_layers.5.output_projection.weight", "f0_dec.estimator_f0.residual_layers.5.output_projection.bias", "f0_dec.estimator_f0.residual_layers.6.dilated_conv.weight", "f0_dec.estimator_f0.residual_layers.6.dilated_conv.bias", "f0_dec.estimator_f0.residual_layers.6.diffusion_projection.weight", "f0_dec.estimator_f0.residual_layers.6.diffusion_projection.bias", "f0_dec.estimator_f0.residual_layers.6.conditioner_projection.weight", "f0_dec.estimator_f0.residual_layers.6.conditioner_projection.bias", "f0_dec.estimator_f0.residual_layers.6.output_projection.weight", "f0_dec.estimator_f0.residual_layers.6.output_projection.bias", "f0_dec.estimator_f0.residual_layers.7.dilated_conv.weight", "f0_dec.estimator_f0.residual_layers.7.dilated_conv.bias", "f0_dec.estimator_f0.residual_layers.7.diffusion_projection.weight", "f0_dec.estimator_f0.residual_layers.7.diffusion_projection.bias", "f0_dec.estimator_f0.residual_layers.7.conditioner_projection.weight", "f0_dec.estimator_f0.residual_layers.7.conditioner_projection.bias", "f0_dec.estimator_f0.residual_layers.7.output_projection.weight", "f0_dec.estimator_f0.residual_layers.7.output_projection.bias", "f0_dec.estimator_f0.residual_layers.8.dilated_conv.weight", "f0_dec.estimator_f0.residual_layers.8.dilated_conv.bias", "f0_dec.estimator_f0.residual_layers.8.diffusion_projection.weight", "f0_dec.estimator_f0.residual_layers.8.diffusion_projection.bias", "f0_dec.estimator_f0.residual_layers.8.conditioner_projection.weight", "f0_dec.estimator_f0.residual_layers.8.conditioner_projection.bias", "f0_dec.estimator_f0.residual_layers.8.output_projection.weight", "f0_dec.estimator_f0.residual_layers.8.output_projection.bias", "f0_dec.estimator_f0.residual_layers.9.dilated_conv.weight", "f0_dec.estimator_f0.residual_layers.9.dilated_conv.bias", "f0_dec.estimator_f0.residual_layers.9.diffusion_projection.weight", "f0_dec.estimator_f0.residual_layers.9.diffusion_projection.bias", "f0_dec.estimator_f0.residual_layers.9.conditioner_projection.weight", "f0_dec.estimator_f0.residual_layers.9.conditioner_projection.bias", "f0_dec.estimator_f0.residual_layers.9.output_projection.weight", "f0_dec.estimator_f0.residual_layers.9.output_projection.bias", "f0_dec.estimator_f0.residual_layers.10.dilated_conv.weight", "f0_dec.estimator_f0.residual_layers.10.dilated_conv.bias", "f0_dec.estimator_f0.residual_layers.10.diffusion_projection.weight", "f0_dec.estimator_f0.residual_layers.10.diffusion_projection.bias", "f0_dec.estimator_f0.residual_layers.10.conditioner_projection.weight", "f0_dec.estimator_f0.residual_layers.10.conditioner_projection.bias", "f0_dec.estimator_f0.residual_layers.10.output_projection.weight", "f0_dec.estimator_f0.residual_layers.10.output_projection.bias", "f0_dec.estimator_f0.residual_layers.11.dilated_conv.weight", "f0_dec.estimator_f0.residual_layers.11.dilated_conv.bias", "f0_dec.estimator_f0.residual_layers.11.diffusion_projection.weight", "f0_dec.estimator_f0.residual_layers.11.diffusion_projection.bias", "f0_dec.estimator_f0.residual_layers.11.conditioner_projection.weight", "f0_dec.estimator_f0.residual_layers.11.conditioner_projection.bias", "f0_dec.estimator_f0.residual_layers.11.output_projection.weight", "f0_dec.estimator_f0.residual_layers.11.output_projection.bias", "f0_dec.estimator_f0.residual_layers.12.dilated_conv.weight", "f0_dec.estimator_f0.residual_layers.12.dilated_conv.bias", "f0_dec.estimator_f0.residual_layers.12.diffusion_projection.weight", "f0_dec.estimator_f0.residual_layers.12.diffusion_projection.bias", "f0_dec.estimator_f0.residual_layers.12.conditioner_projection.weight", "f0_dec.estimator_f0.residual_layers.12.conditioner_projection.bias", "f0_dec.estimator_f0.residual_layers.12.output_projection.weight", "f0_dec.estimator_f0.residual_layers.12.output_projection.bias", "f0_dec.estimator_f0.residual_layers.13.dilated_conv.weight", "f0_dec.estimator_f0.residual_layers.13.dilated_conv.bias", "f0_dec.estimator_f0.residual_layers.13.diffusion_projection.weight", "f0_dec.estimator_f0.residual_layers.13.diffusion_projection.bias", "f0_dec.estimator_f0.residual_layers.13.conditioner_projection.weight", "f0_dec.estimator_f0.residual_layers.13.conditioner_projection.bias", "f0_dec.estimator_f0.residual_layers.13.output_projection.weight", "f0_dec.estimator_f0.residual_layers.13.output_projection.bias", "f0_dec.estimator_f0.residual_layers.14.dilated_conv.weight", "f0_dec.estimator_f0.residual_layers.14.dilated_conv.bias", "f0_dec.estimator_f0.residual_layers.14.diffusion_projection.weight", "f0_dec.estimator_f0.residual_layers.14.diffusion_projection.bias", "f0_dec.estimator_f0.residual_layers.14.conditioner_projection.weight", "f0_dec.estimator_f0.residual_layers.14.conditioner_projection.bias", "f0_dec.estimator_f0.residual_layers.14.output_projection.weight", "f0_dec.estimator_f0.residual_layers.14.output_projection.bias", "f0_dec.estimator_f0.residual_layers.15.dilated_conv.weight", "f0_dec.estimator_f0.residual_layers.15.dilated_conv.bias", "f0_dec.estimator_f0.residual_layers.15.diffusion_projection.weight", "f0_dec.estimator_f0.residual_layers.15.diffusion_projection.bias", "f0_dec.estimator_f0.residual_layers.15.conditioner_projection.weight", "f0_dec.estimator_f0.residual_layers.15.conditioner_projection.bias", "f0_dec.estimator_f0.residual_layers.15.output_projection.weight", "f0_dec.estimator_f0.residual_layers.15.output_projection.bias", "f0_dec.estimator_f0.residual_layers.16.dilated_conv.weight", "f0_dec.estimator_f0.residual_layers.16.dilated_conv.bias", "f0_dec.estimator_f0.residual_layers.16.diffusion_projection.weight", "f0_dec.estimator_f0.residual_layers.16.diffusion_projection.bias", "f0_dec.estimator_f0.residual_layers.16.conditioner_projection.weight", "f0_dec.estimator_f0.residual_layers.16.conditioner_projection.bias", "f0_dec.estimator_f0.residual_layers.16.output_projection.weight", "f0_dec.estimator_f0.residual_layers.16.output_projection.bias", "f0_dec.estimator_f0.residual_layers.17.dilated_conv.weight", "f0_dec.estimator_f0.residual_layers.17.dilated_conv.bias", "f0_dec.estimator_f0.residual_layers.17.diffusion_projection.weight", "f0_dec.estimator_f0.residual_layers.17.diffusion_projection.bias", "f0_dec.estimator_f0.residual_layers.17.conditioner_projection.weight", "f0_dec.estimator_f0.residual_layers.17.conditioner_projection.bias", "f0_dec.estimator_f0.residual_layers.17.output_projection.weight", "f0_dec.estimator_f0.residual_layers.17.output_projection.bias", "f0_dec.estimator_f0.residual_layers.18.dilated_conv.weight", "f0_dec.estimator_f0.residual_layers.18.dilated_conv.bias", "f0_dec.estimator_f0.residual_layers.18.diffusion_projection.weight", "f0_dec.estimator_f0.residual_layers.18.diffusion_projection.bias", "f0_dec.estimator_f0.residual_layers.18.conditioner_projection.weight", "f0_dec.estimator_f0.residual_layers.18.conditioner_projection.bias", "f0_dec.estimator_f0.residual_layers.18.output_projection.weight", "f0_dec.estimator_f0.residual_layers.18.output_projection.bias", "f0_dec.estimator_f0.residual_layers.19.dilated_conv.weight", "f0_dec.estimator_f0.residual_layers.19.dilated_conv.bias", "f0_dec.estimator_f0.residual_layers.19.diffusion_projection.weight", "f0_dec.estimator_f0.residual_layers.19.diffusion_projection.bias", "f0_dec.estimator_f0.residual_layers.19.conditioner_projection.weight", "f0_dec.estimat

**Comment by xinxinye000** [comment]
I defined the end of --model=./model/base.py 
--model=./module/modules.py

**Comment by hayeong0** [comment]
Hello,
It seems that you are referring to train.py, but based on the logs, it looks like you are trying to run inference. 
Please use the `infer.sh` script, as mentioned in the README, to run the inference using the pre-trained model's checkpoint.

**Comment by xinxinye000** [comment]
> Hello, It seems that you are referring to train.py, but based on the logs, it looks like you are trying to run inference. Please use the `infer.sh` script, as mentioned in the README, to run the inference using the pre-trained model's checkpoint.


Hi, actually, I have two questions.
1. When I used the infer.sh script, I also got an error:
D:\Anaconda\000\envs\cuda113\python.exe E:\Code_test\88_wav-wav\01\Diff-HierVC-master\inference.py 
>> Initializing Inference Process...
Removing weight norm...
>> Converting each utterance...
Traceback (most recent call last):
  File "E:\Code_test\88_wav-wav\01\Diff-HierVC-master\inference.py", line 140, in <module>
    main()
  File "E:\Code_test\88_wav-wav\01\Diff-HierVC-master\inference.py", line 137, in main
    inference(a)
  File "E:\Code_test\88_wav-wav\01\Diff-HierVC-master\inference.py", line 109, in inference
    c = model.infer_vc(src_mel, w2v_x, f0_norm_x, f0_x, src_length, trg_mel, trg_length, 
  File "E:\Code_test\88_wav-wav\01\Diff-HierVC-master\model\diffhiervc.py", line 163, in infer_vc
    spk, y_f0_hat, enc_f0 = self.encoder.f0_predictor(x_w2v, x_f0_norm, y, y_mask, f0_mask)
  File "E:\Code_test\88_wav-wav\01\Diff-HierVC-master\model\diffhiervc.py", line 119, in f0_predictor
    enc_f0 = self.f0_enc(F.relu(content_f+norm_f0), f0_mask, g=g)
  File "D:\Anaconda\000\envs\cuda113\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Code_test\88_wav-wav\01\Diff-HierVC-master\model\diffhiervc.py", line 60, in forward
    x = self.pre(x * x_mask) * x_mask
RuntimeError: The size of tensor a (873) must match the size of tensor b (1200) at non-singleton dimension 2

进程已结束，退出代码为 1




2.
The long error I mentioned above was the error that occurred when I put the model file generated by train to the inference after running train.py.
According to my understanding, the train.py file is used to generate a model file, and the generated model file should be available for inference.
So I was wondering, when I train with train.py, I'm asked to type --model and ----config.
The command I used was train.py --model=./model/base.py --config=./ckpt/config.json
Using train.py is there a corresponding.sh file to refer to? I want to train my own data set.

**Comment by hayeong0** [comment]
I see. Sorry for the confusion. 
--config is the model's configuration file (the same JSON file you mentioned), and --model refers to the name of the model you want to train.

So, you can use this example sh:
CUDA_VISIBLE_DEVICES=0,1 python3 train.py -c [config file path] -m [model_name]

**Comment by xinxinye000** [comment]
> I see. Sorry for the confusion. --config is the model's configuration file (the same JSON file you mentioned), and --model refers to the name of the model you want to train.
> 
> So, you can use this example sh: CUDA_VISIBLE_DEVICES=0,1 python3 train.py -c [config file path] -m [model_name]

Can I ask if the model_diffhier.pth mentioned in infer.sh was trained in train.py? If so, how do I train train.py to get model_diffhier.pth? Can you provide the --model when you run trian.py?

**Comment by hayeong0** [comment]
The pre-trained checkpoint provided in this repository is a model trained using train.py and model.py. 
We are also providing the training code to allow you to reproduce the performance of the trained model.

You can train the model using the following shell command:
CUDA_VISIBLE_DEVICES=0,1 python3 train.py -c configs/config_16k.json -m diff-hierVC

After training, a directory named diff-hierVC (or whatever name you set after the -m option) will be created. 
Inside this directory, the model checkpoints will be saved in the format G_[step number].pth, for example, G_200000.pth. 
I renamed the file to model_diffhier.pth for upload purposes.

If you have any further questions, feel free to ask!

**Comment by xinxinye000** [comment]
> The pre-trained checkpoint provided in this repository is a model trained using train.py and model.py. We are also providing the training code to allow you to reproduce the performance of the trained model.
> 
> You can train the model using the following shell command: CUDA_VISIBLE_DEVICES=0,1 python3 train.py -c configs/config_16k.json -m diff-hierVC
> 
> After training, a directory named diff-hierVC (or whatever name you set after the -m option) will be created. Inside this directory, the model checkpoints will be saved in the format G_[step number].pth, for example, G_200000.pth. I renamed the file to model_diffhier.pth for upload purposes.
> 
> If you have any further questions, feel free to ask!

Thank you for your reply and wish you every success in your work.
